// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartParking.Api.Data;

#nullable disable

namespace SmartParking.Api.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20261007143205_InitialParkingSchema")]
    partial class InitialParkingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.Api.Models.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Analyzer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "CreatedAt");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("SmartParking.Api.Models.OccupancyResult", b =>
                {
                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParkingSpaceId")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<bool>("Occupied")
                        .HasColumnType("boolean");

                    b.HasKey("AnalysisRunId", "ParkingSpaceId");

                    b.HasIndex("ParkingSpaceId");

                    b.ToTable("OccupancyResults");
                });

            modelBuilder.Entity("SmartParking.Api.Models.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("ParkingLots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Central Park · Lot A"
                        });
                });

            modelBuilder.Entity("SmartParking.Api.Models.ParkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "Label")
                        .IsUnique();

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "A01",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Label = "A02",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 3,
                            Label = "A03",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 4,
                            Label = "A04",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 5,
                            Label = "A05",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 6,
                            Label = "A06",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 7,
                            Label = "A07",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 8,
                            Label = "A08",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 9,
                            Label = "A09",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 10,
                            Label = "A10",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 11,
                            Label = "A11",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 12,
                            Label = "A12",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 13,
                            Label = "B01",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 14,
                            Label = "B02",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 15,
                            Label = "B03",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 16,
                            Label = "B04",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 17,
                            Label = "B05",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 18,
                            Label = "B06",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 19,
                            Label = "B07",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 20,
                            Label = "B08",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 21,
                            Label = "B09",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 22,
                            Label = "B10",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 23,
                            Label = "B11",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 24,
                            Label = "B12",
                            ParkingLotId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("SmartParking.Api.Models.AnalysisRun", b =>
                {
                    b.HasOne("SmartParking.Api.Models.ParkingLot", null)
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartParking.Api.Models.OccupancyResult", b =>
                {
                    b.HasOne("SmartParking.Api.Models.AnalysisRun", null)
                        .WithMany("Results")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartParking.Api.Models.ParkingSpace", null)
                        .WithMany()
                        .HasForeignKey("ParkingSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartParking.Api.Models.ParkingSpace", b =>
                {
                    b.HasOne("SmartParking.Api.Models.ParkingLot", null)
                        .WithMany("Spaces")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartParking.Api.Models.AnalysisRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SmartParking.Api.Models.ParkingLot", b =>
                {
                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
